name: Deploy to GKE

on:
  push:
    branches:
      - ga6-cd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: hybrid-shine-474105-e1

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t us-central1-docker.pkg.dev/hybrid-shine-474105-e1/iris-api-repo/iris-api:latest .

      - name: Push Docker image
        run: docker push us-central1-docker.pkg.dev/hybrid-shine-474105-e1/iris-api-repo/iris-api:latest

      - name: Set up GKE credentials
        run: gcloud container clusters get-credentials iris-cluster --region us-central1 --project hybrid-shine-474105-e1

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deploy.yaml
          kubectl rollout status deployment/iris-api

